server:
  port: 8081
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://db:5432/bank?currentSchema=bank_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        format_sql: true